CRMProject.Web/Controllers/ProblemController.cs
using CRMProject.Data;
using CRMProject.Service.Admin;
using CRMProject.ViewModels.Admin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using CRMProject.Web.Controllers.Abstract;

namespace CRMProject.Web.Controllers
{

    [Authorize]
    public class ProblemController : AdminBaseController
    {
        // GET: Problem
        public ProblemService _problemService;
        public ProblemController(ProblemService problemService)
        {
            _problemService = problemService;
        }
        public ActionResult Index()
        {
          var model=  _problemService.Get();
            return View(model);
        }
        public ActionResult Yeni()
        {


            var model = _problemService.Get2();
            return View(model);



        }
        public async Task<ActionResult> Kaydet(ProblemViewModel problemViewModel)
        {
            var callResult=await  _problemService.Get3(problemViewModel);
            if (callResult.Success)
            {

                ModelState.Clear();
                var problemId = (int)callResult.Item;
                var viewModel = await _problemService.GetProblemListViewAsync(problemId);
                var jsonResult = Json(
                    new
                    {
                        success = true,
                        responseText = RenderPartialViewToString("~/Views/Problem/DisplayTemplates/ProblemViewModel.cshtml", viewModel),
                        item = viewModel
                    });
                jsonResult.MaxJsonLength = int.MaxValue;
                return jsonResult;
            }
            foreach (var error in callResult.ErrorMessages)
            {
                ModelState.AddModelError("", error);
            }

            return RedirectToAction("Index");
        }

        public  ActionResult Delete(int problemId)
        {
            var model = new ProblemViewModel()
            {
                Id = problemId
            };
            return  PartialView("/Views/Problem/_problemDelete.cshtml",model);
        }
        [HttpPost]
        public async Task<ActionResult> Delete(ProblemViewModel problemViewModel)
        {
            var callResult = await _problemService.DeleteAsync(problemViewModel.Id);
            if (callResult.Success)
            {

                ModelState.Clear();
                return Json(
                    new
                    {
                        success = true,
                        warningMessages = callResult.WarningMessages,
                        successMessages = callResult.SuccessMessages,
                    });
            }
            return Json(
                new
                {
                    success = false,
                    errorMessages = callResult.ErrorMessages,
                    responseText = RenderPartialViewToString("~/Views/Problem/_problemDelete.cshtml", problemViewModel)
                });
        }





        }

    }

CRMProject.Web/Views/Problem/Index.cshtml
@using CRMProject.ViewModels.Admin
@model IEnumerable<ProblemViewModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<table class="table table-bordered">
    <thead>
        <tr>
            <td>Ad</td>
        </tr>
    </thead>
    <tbody id="problemform">
        @Html.DisplayFor(m => m);

    </tbody>
</table>
<a class="btn btn-default btn-sm"
   data-modal-form="true"
   data-modal-size="modal-lg"
   data-modal-append="tbody#problemform"
   data-modal-title="Problem ekle"
   data-hook-beforeunload="true"
   href="@Url.Action("Yeni", "Problem", routeValues: new {Area =string.Empty})">
    <i class="fa fa-plus"></i>Problem Ekle
</a>

CRMProject.Web/Views/Problem/Yeni.cshtml
@model CRMProject.ViewModels.Admin.ProblemViewModel

<!-- Modal -->

              
        
            <div class="modal-body">
                @using (Html.BeginForm("Kaydet", "Problem", FormMethod.Post))
                {

                    <div class="form-group">
                        @Html.LabelFor(x => x.Name )
                        @Html.TextBoxFor(x=>x.Name,new { @class = "form-control" })) 
                       
                    </div>
                    
                    @*<div class="form-group">
                            @Html.LabelFor(x => x.taskSet.Roles.Role)
                            @Html.DropDownListFor(x => x.taskSet.RoleId, new SelectList(Model.Roles, "Id", "Role", Model.taskSet.RoleId), new { @class = "form-control" })
                        </div>*@
                    <!--<div class="form-group">-->
                    @*@Html.LabelFor(x => x.taskSet.Users.UserName)
                            @Html.DropDownListFor(x => x.taskSet.UserId, new SelectList(Model.Users, "Id", "UserName", Model.taskSet.UserId), new { @class = "form-control" })
                        </div>*@
                  
                    <div class="modal-footer">
                        @*@if (Model.taskSet.Roles.Role == ViewBag.role)
                            {*@
                        <button type="submit" class="btn btn-default">Kaydet</button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

                        @*}*@
                    </div>

                }
            </div>

CRMProject.Web/Views/Problem/_problemDelete.cshtml
@model CRMProject.ViewModels.Admin.ProblemViewModel


@using (Html.BeginForm("Delete", "Problem", new { Area = String.Empty }, FormMethod.Post))
{

    @Html.HiddenFor(a => a.Id)
    <label>Silmek istediğinize emin misiniz?</label>
    <hr />
    <div class="form-group form-group-sm row">
        <div class="col-xs-12">
            <button type="submit" class="btn btn-primary pull-right margin-left10"><span class="fa fa-check"></span>&nbsp;&nbsp;Kaydet</button>
            <button class="btn btn-danger pull-right" type="button" data-dismiss="modal"><span class="fa fa-times"></span>&nbsp;&nbsp;İptal</button>
        </div>
    </div>
    <div class="clearfix"></div>
}